[workspace]
resolver = "3"
members = [
    "arch/x86_64", 
    "arch/xtensa",
    "boot",
    "kernel",
    "mm",
    "esp32"
]

exclude = [
    ".git-blame-ignore-revs",
    ".gitignore",
]

[workspace.dependencies]
uefi = "0.39.0"

boot =      { path = "boot" }
mm =        { path = "mm" }

x86_64 =    { path = "arch/x86_64" }
xtensa =    { path = "arch/xtensa" }

esp32 =     { path = "esp32" }


[workspace.package]
version = "0.8.3"
edition = "2024"
authors = ["Alessio Maroni"]
license = "MIT or Apache-2.0"
readme = "README"
repository = "https://github.com/ale0Maro/Hugin"

[profile.dev]
opt-level = 0
debug = 2
overflow-checks = true 
debug-assertions = true
lto = false
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
debug = false
strip = "symbols"
