[workspace]
resolver = "3"
members = [
    "boot",
    "kernel",
    "kernel/mm",
    "kernel/io",
    "arch/x86_64",
    "kernel/time",
    "soc/esp32",
    "boards/esp32-devkit-v1"]

exclude = [
    ".git-blame-ignore-revs",
    ".gitignore",
]

[workspace.dependencies]
uefi = "0.39.0"

boot =      { path = "boot" }
mm =        { path = "kernel/mm" }
io =        { path = "kernel/io" }
time =      { path = "kernel/time" }
esp32 =     { path = "soc/esp32" }
esp32-devkit-v1 = { path = "boards/esp32-devkit-v1" }


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Hugin Kernel Project"]
license = "MIT or Apache-2.0"
readme = "README"
repository = "https://github.com/alessioMaroni/Hugin"

[profile.dev]
opt-level = 0
debug = 2
overflow-checks = true 
debug-assertions = true
lto = false
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
debug = false
strip = "symbols"
